name: Build

strategy:
  matrix:
    os: [ubuntu-latest]

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      - name: Install OS dependencies
        run: sudo apt-get install -qy curl jq
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Install dependencies
        run: ./scripts/setup.sh
      - name: Build
        run: ./scripts/build.sh
