name: Test

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Install dependencies
        run: ./scripts/setup.sh
      - name: Run tests
        run: npm test
